apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/devtalles-432023/image-registry-talles/payments-ms
        name: payments-ms
        resources: {}
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: STRIPE_SUCCESS_URL
            value: "http://localhost:3000/success"
          - name: STRIPE_CANCEL_URL
            value: "http://localhost:3000/cancel"
          - name: STRIPE_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_secret
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_endpoint_secret
status: {}
