apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30008
    protocol: TCP
  selector:
    app: client-gateway
  type: NodePort
status:
  loadBalancer: {}
